### PR TITLE
operator overloading

### PR DESCRIPTION
**Pull request by noklam**
Related Issue #3 
Changes:
* Overloading operator to make the syntax simpler.

If this is something interesting I can help adding the corresponding doc

Usage:
## Before
image
image

## After
image
image

### CODE REVIEW

**Comment by jph00** [comment]
@noklam sorry I missed this! Feel free to at-mention me to ensure I get notified.

I think the operator should be `+=`, since it's modifying the LHS - what do you think?

**Comment by noklam** [comment]
@jph00  Thx, I think `+=` make sense, unfortunately it seems not as straight forward as changing `__add__` to `__iadd__`, I couldn't make it work.

**Comment by jph00** [comment]
Oh that's interesting. What happened when you tried that?

**Comment by noklam** [comment]
image
Instead of returning a `pydot` object, it return a fastai `L`
@jph00

**Comment by noklam** [comment]
@jph00 @mentioning again in case you missed it.

**Comment by jph00** [comment]
Thanks - I did miss it. I don't think we can use `+` in this way. At least for me, I just can't get my head around it! I'm fine with `>>` however. Maybe remove `+` for now, since `+=` isn't working?

**Pull request closed without merging**
